### ISSUE TITLE
Rename 'Check your data' buttons to avoid confusion

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#102]
Currently there are two buttons named 'Submit' on the Data Quality Tool, which is causing confusion when people come to move from checking their data to submitting it to the registry.

Longer term (and as part of our DQT project next year) we should consider the UX of this, but in the short term, could we improve things by renaming the buttons used to check data to help avoid confusion?

There are three buttons used for testing data

Option 1 - rename all three - 'Check data'
Option 2 - rename each to the action 'Upload', 'Link', 'Paste'

Or is there another option?

**Comment by mariongalley** [comment]
@michaelwood This is a quick win, could you look at whether we could get this done in the sort term?

**Comment by KDuerden** [comment]
Just to add it would be great if this could be done via incremental improvements, prior to the larger development sprint.

**Comment by michaelwood** [comment]
Option 1 chosen (discussion with @mariongalley)

The buttons are provided by `lib-cove-web` rather than in 360Giving's cove, however given that we're going to want to deviate from the library provided templates in the near future I've copied this particular one in.
