### ISSUE TITLE
Modal on Accuracy tests is transparent, freezes tool

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#122]
Modal on Accuracy tests is transparent, can't be closed and tool needs to be reloaded to reset. 

This issue only impacts Accuracy, the Usefulness and Summary text modals work as intended.

**Comment by mariongalley** [comment]
@michaelwood I'm still experiencing this, was it deployed to dev?

**Comment by michaelwood** [comment]
Should now be fixed
