### ISSUE TITLE
Conversion errors are easily missed

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#123]
Conversion errors appear in an unformatted way below the summary.

The lack of formatting means the information is easily missed. Some kind of formatting or alert is needed to make sure data with conversion errors gets attention from the user.

It appears that the Figma design does not include conversion errors, potentially because test files provided did not include these issues.

![image](https://github.com/user-attachments/assets/86a9b4da-7881-4db1-aaa2-2fbf5caad327)

**Comment by michaelwood** [comment]
As a mitigation I've moved this up higher in the summary area and added a table of contents with the error counts. We'll probably want to come back to this with a design iteration but this might be passable for v1.

![Image](https://github.com/user-attachments/assets/c83c3d64-3555-4f52-8149-af865bcdd43c)
