### ISSUE TITLE
US DQT-014 - Files with no 360 headings appear to pass Accuracy and Usefulness checks

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#125]
Files with no 360 headings tests fail Validity, but have a pass state for Accuracy and Usefulness. 

This issue was trigger by testing US DQT-014, but I assume this is caused by 0 errors triggering a positive message state, but in this case it is 0/0 grants with issues, rather than 0/n grants.

This appears to be a bug, but maybe rare enough case, and one that requires data to be fixed and retested, that this is not a high priority (especially if it is hard to fix)

![image](https://github.com/user-attachments/assets/0591967f-46ab-4af3-9bd8-95c0abc88ebe)

**Accuracy feedback**
![image](https://github.com/user-attachments/assets/f962763e-0ac3-4136-8a61-a208fe41cd1d)

**Usefulness feedback**
![image](https://github.com/user-attachments/assets/bc816f5f-6836-4ef4-b7e3-3f74858a1c7b)

Note this only happens for files with no 360 headings. For files with less than 50% headings the error messages work as intended.

**Comment by michaelwood** [comment]
@KDuerden would you be able to attach or link to this data?  this would be useful for our future test cases. Thanks
