### ISSUE TITLE
Deploy is going to break soon cos of rfc6266

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/dataquality#15]
We have rfc6266 in the req.in.

This won't install locally when I make a new virtualenv. It appears to be this error: https://github.com/g2p/rfc6266/issues/17

Only seen locally so far but it will affect the server at some point so we should sort this.

**Comment by michaelwood** [comment]
Thanks yes, we've seen this also in https://github.com/ThreeSixtyGiving/datagetter/commit/78cff948ca82f3a00cb5bdd0040795c6fddf8a03

Not quite sure what rfc6266 it is used for here though? possibly nothing!

**Comment by odscjames** [comment]
I also just found https://github.com/ThreeSixtyGiving/datagetter/pull/25

I can't find the use of rfc6266 in this codebase and the commit that introduces it says "dataquality: Add files from 360 cove and datatester" so I'm hoping I can just make sure datagetter is up to date here then remove the requirement. 

We should also check elsewhere in the 360 estate, as requirements seem to have been copied around at points.

**Comment by odscjames** [comment]
> We should also check elsewhere in the 360 estate, as requirements seem to have been copied around at points.

It's also in datastore, but there it's via datagetter so when dependencies are updated the problem will resolve itself.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cove & rfc6266](https://trello.com/c/EFv1ovWr/225-cove-rfc6266)
