### ISSUE TITLE
"requirements_dev.in" should include "-r requirements_cove.txt"

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/dataquality#19]
This is standard in our other work eg https://github.com/openownership/cove-bods/blob/master/requirements_dev.in

It avoids a problem where by it is sometimes possible to generate 2 lock files with different versions of the same library. This means the tests will not be running against the same version of the libraries as live. This happened in #10 .

An additional problem here is that it is easy to miss this situation. In fact, when you have include the other lock file you will sometimes get big errors when trying to update dependencies as there isn't a possible resolution - but it is much better to be made aware of this and fix it straight away than to have a problem we aren't aware of.

However, it is not so easy in this case - as this repository has both the library and the app, whatever solution we put in here needs to work for both of them.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix requirements development files loader](https://trello.com/c/BqGulDMn/257-fix-requirements-development-files-loader)
