### ISSUE TITLE
Reduce text size in DQT feedback making results difficult to read 

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#28]
Using Chrome, Firefox and MS Edge, the font size for DQT feedback is now very small.

https://dataquality.threesixtygiving.org/results/d0643d21-c595-441a-b424-d9ada31c30da

![image](https://user-images.githubusercontent.com/20462640/162905792-c7287650-b6d5-4794-a59e-723f29da3845.png)

**Comment by mariongalley** [comment]
+1 it's illegibly small for me

**Comment by michaelwood** [comment]
Hm this is coming from the design system style, by default a table has a font size of 0.9rem (which is a weirdly tiny size) https://github.com/ThreeSixtyGiving/360-ds/blob/master/src/components/03-components/table/table.scss#L6 . We had to add the design system in order to use the cookie consent component.

Options are:
1) Hack in an override for the font size into cove (~hour)
2) Spend time/budget integrating the design system into cove (~days)
3) Remove cookie consent and analytics (~hour)
4) Attempt to do a partial integration of the design system just for those tables (~3 hours)

**Comment by michaelwood** [comment]
> Hm this is coming from the design system style, by default a table has a font size of 0.9rem (which is a weirdly tiny size) 
(Weirdly tiny actually is just because of the two different fonts, the one loaded via bootstrap-360 and the one via 360-ds)

**Comment by KDuerden** [comment]
Thanks Michael

We're considering between option 1 or 4.
Is there future-proofing that will come from investing a bit more time in option 4 or will it be too localised to the tables to benefit other parts of the DQT?

I think long term we need to look at progressing with option 2 but it's not a priority for now

**Comment by michaelwood** [comment]
> We're considering between option 1 or 4. Is there future-proofing that will come from investing a bit more time in option 4 or will it be too localised to the tables to benefit other parts of the DQT?
> 

Option 4, would be future proof if you don't envisage fundamentally changing the layout and designed UX of the DQT (i.e. you're only going to change how it looks) when option 2 happens.

**Comment by michaelwood** [comment]
Thought of another probably better option which would be to remove the font styling from the boostrap-360 theme and allow the 360-ds to take over that styling using the new fonts. (~hours)

**Comment by mariongalley** [comment]
> Thought of another probably better option which would be to remove the font styling from the boostrap-360 theme and allow the 360-ds to take over that styling using the new fonts. (~hours)

If that's the better option then I think go for it

**Comment by michaelwood** [comment]
![Screenshot from 2022-04-13 16-08-34](https://user-images.githubusercontent.com/493697/163211894-725a97cd-de4c-4e69-8422-2acfa1d41111.png)

I also changed the colour for links from the old 360 orange to the new 360-ds dark-teal as I noticed the link text on the cookie consent box also isn't very readable (good for new accessibility standards currently anyway).
