### ISSUE TITLE
Make links consistent within the DQT feedback

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/dataquality#31]
Relates to #28 @michaelwood 

The formatting of hyperlinks is inconsistent in the DQT now - underlined in feedback messages but not in the rest of the tool. Please add underlining to links elsewhere.

Happy for this to be handled as an iterative improvement this month or next month.

**Comment by michaelwood** [comment]
This has come up before with other products so am wondering if we should try at sorting this out at the [360-ds style globally level](https://github.com/ThreeSixtyGiving/360-ds/issues/59). It will take more time but I think this is going to be a recurring issue and it would be good to fix at the source.

**Comment by michaelwood** [comment]
[We're going to make links inside paragraphs underlined by default in 360-ds.](https://github.com/ThreeSixtyGiving/360-ds/issues/59)
