### ISSUE TITLE
Remove "This tool is alpha." banner and EN/ES dropdown from Common Errors and Ts&Cs pages

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/dataquality#58]
![image](https://user-images.githubusercontent.com/82958988/183080176-ef4b59a7-a191-462f-a9d7-3c3639a5ed07.png)

The [Common Errors](https://dataquality.threesixtygiving.org/common_errors) and [Ts&Cs](https://dataquality.threesixtygiving.org/terms/) pages of the DQT both have this banner and drop-down which should be removed, as it is no longer in alpha and the drop-down does nothing.

**Comment by mariongalley** [comment]
@michaelwood Will this be deployed alongside self-registration or at some other (earlier) time? I don't think it's urgent at all but do want to test it in the live DQT.

**Comment by michaelwood** [comment]
> Thanks for the fix! @michaelwood Will this be deployed alongside self-registration or at some other (earlier) time? I don't think it's urgent at all but do want to test it in the live DQT.

Yes I added this to the self registration branch of work so it will be deployed along side the self-registration stuff. Happy to  port over the fix to the current live if you'd like.

**Comment by mariongalley** [comment]
> Happy to port over the fix to the current live if you'd like.

No it's OK, thanks though

**Comment by mariongalley** [comment]
This is now live!
