### ISSUE TITLE
Codelist links are broken

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/dataquality#80]
When incorrect codes are included in closed codelist the DQT provides an error message with a hyperlink to the codelist, however these links all direct to the wrong place, [for example](http://datapipes.herokuapp.com/csv/html/?url=https://raw.githubusercontent.com/ThreeSixtyGiving/standard/master/codelists/regrantType.csv)

![image](https://user-images.githubusercontent.com/20462640/222141365-024068a2-683e-414d-8eb3-1e47bf570232.png)

Also to note, there are 5 codelist fields with errors in the example file being tested but only 4 of them are listed as having problems - [see feedback](https://dataquality.threesixtygiving.org/results/9b26e85e-89d5-4217-a695-2355df7ce911)

There are also only 'Other errors' with specifics about the issue for currency and country code (which are the two enum'd codelists, so is this influencing this behavour?)

The dummy data being tested is attached.
[Dummy-data-for-testing-codeerrors.xlsx](https://github.com/ThreeSixtyGiving/dataquality/files/10861010/Dummy-data-for-testing-codeerrors.xlsx)

**Comment by KDuerden** [comment]
Thanks Ben

> Would you like the link to go to https://standard.threesixtygiving.org/en/latest/technical/codelists/#regrant-type instead?

Yes, I think linking to the more user friendly codelist tables for those we manage via [CSVs would be great](https://standard.threesixtygiving.org/en/latest/technical/codelists/#the-codelists-used-in-the-standard). Not sure what to suggest for the enums, as we wanted to avoid having to put such long lists in the docs.

> Looks like "To Individuals Details:Grant Purpose" is missing, I'll do some digging into why.

It did appear at points I played around by adding and removing errors, so I don't think it's a fixed issue effecting just one codelist, but something to do with a max number to show maybe?

**Comment by Bjwebb** [comment]
I think everything in this issue has been done, except for fixing the display of enums vs non-enums, which I've split out into it's own issue https://github.com/ThreeSixtyGiving/dataquality/issues/86
