### ISSUE TITLE
Percentages for organisation usefulness tests not correct

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/dataquality#88]
We currently have an issue where any of the tests which do checks based on data in the recipientOrganization object give the wrong total percentage of issues. This is because the % calculation: `total_issues / total_grants` is not correct if the file contains a mixture of grants to recipient organisations and grants to individuals.

- RecipientOrg360GPrefix
- RecipientOrgUnrecognisedPrefix
- RecipientOrgCharityNumber
- RecipientOrgCompanyNumber
- NoRecipientOrgCompanyCharityNumber
- IncompleteRecipientOrg
- OrganizationIdLooksInvalid

This is a blocker for the quality dashboard work. Fixing this is difficult because we need to know the total of each type of recipient and we only know that once we've completed working through the file, by which time all the tests have been run.

**Comment by michaelwood** [comment]
Idea for this is something around splitting the file into individuals and organisations in the dqt application and process them as two runs of the dqt.

**Comment by michaelwood** [comment]
I think I've fixed this now:

![image](https://user-images.githubusercontent.com/493697/234066682-5729f80b-825e-4b2d-b486-249a67a743ea.png)

To make it clearer which % the number is refering to i've added "recipient organisation" grants, if we had any usefulness tests for individuals it would say "recipient individuals" . Tests which are relevant to all grants have no additional copy.

@KDuerden @mariongalley does that sound like a good way forward?

**Comment by mariongalley** [comment]
@michaelwood Yes that sounds good. We should have usefulness tests for individuals that recommend using the individuals codelists, and strongly warns not to include DEI data or postcodes

**Comment by michaelwood** [comment]
Fix now deployed
